# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75bbdd670794f0e423bda2b062f5edd1f8cd6ecec5f3e5ed9e918819b1f25745a4372221ee4b9cc1c324d342ff5247746a2244aae4d26133fec67bc6c619c638

test:
  secret_key_base: ae627e20582fddd0891bf6d880f0b0d82b7d79cd8cc99083b0276366622063f45fe72d3aa9b2b5e4c2b876f0d36f60018c8af0a25261efa38519c5388c47847e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
